# parameters configuration
mode: train
root: data/
predefined_dataset: MNIST
classes: ["normal", "abnormal"]
max_samples: null
batch_size: 32
num_workers: 0
device: cuda
lr: 1e-3
in_chans: 1
input_height: 32
latent_dim: 256
generator_feature_dim: 64
discriminator_feature_dim: 64
adversarial_weight: 1
reconstruction_weight: 50
encoding_weight: 1
checkpoint_path: null
seed: 0
early_stopping: True
patience: 3
default_root_dir: save/
gpus: -1
precision: 32
max_epochs: 100
color_space: L # (8-bit pixels, black and white)
threshold: null

# transforms configuration
transforms_config:
  train:
    Resize:
      - 32
      - 32
    ToTensor:

  val:
    Resize:
      - 32
      - 32
    ToTensor:

  test:
    Resize:
      - 32
      - 32
    ToTensor:

  predict:
    Resize:
      - 32
      - 32
    ToTensor:

# target transforms configuration
target_transforms_config:
  train: null

  val: null

  test: null

  predict: null

# optimizers configuration
optimizers_config:
  Adam:
    betas:
      - 0.9
      - 0.999
    eps: 1e-08
    weight_decay: 0
    amsgrad: False

# learning rate schedulers configuration
lr_schedulers_config:
  CosineAnnealingLR:
    T_max: 10
