# parameters configuration
mode: train
root: data/
predefined_dataset: CIFAR10
classes: ["normal", "abnormal"]
max_samples: null
batch_size: 32
num_workers: 0
device: cuda
lr: 1e-3
in_chans: 3
input_height: 32
latent_dim: 256
generator_feature_dim: 64
discriminator_feature_dim: 64
adversarial_weight: 1
reconstruction_weight: 50
encoding_weight: 1
checkpoint_path: null
seed: 0
early_stopping: True
patience: 3
default_root_dir: save/
gpus: -1
precision: 32
max_epochs: 100
color_space: RGB # (3x8-bit pixels, true color)
threshold: null
web_interface: True
examples:
  [
    "examples/CIFAR10/appaloosa_s_001946_abnormal.png",
    "examples/CIFAR10/auto_s_000561_abnormal.png",
    "examples/CIFAR10/bufo_marinus_s_001549_abnormal.png",
    "examples/CIFAR10/dog_s_000167_normal.png",
    "examples/CIFAR10/gondola_s_000055_abnormal.png",
    "examples/CIFAR10/wrecker_s_001908_abnormal.png",
  ]
tuning_test: False
cpu_resources_per_trial: 1
gpu_resources_per_trial: 1
num_samples: 100

# transforms configuration
transforms_config:
  train:
    Resize:
      - 32
      - 32
    ToTensor:

  val:
    Resize:
      - 32
      - 32
    ToTensor:

  test:
    Resize:
      - 32
      - 32
    ToTensor:

  predict:
    Resize:
      - 32
      - 32
    ToTensor:

# target transforms configuration
target_transforms_config:
  train: null

  val: null

  test: null

  predict: null

# optimizers configuration
optimizers_config:
  Adam:
    betas:
      - 0.9
      - 0.999
    eps: 1e-08
    weight_decay: 0
    amsgrad: False

# learning rate schedulers configuration
lr_schedulers_config:
  CosineAnnealingLR:
    T_max: 10

# hyperparameter space configuration
hyperparameter_space_config:
  lr:
    uniform:
      lower: 1e-4
      upper: 1e-1

  max_epochs:
    randint:
      lower: 10
      upper: 200
